name: CI

on:
  push:
    branches: 
      - develop-v1
  pull_request:
    branches:
      - develop-v1

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    
    env:
      DOTNET_SKIP_FIRST_TIME_EXPERIENCE: true
      DOTNET_CLI_TELEMETRY_OPTOUT: true
      EVENTFLOW_VERSION: "1.0.${{ github.run_number }}"

    steps:
      - uses: actions/checkout@v2

      - name: Setup .NET Core v2.1
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 2.1.811

      - name: Setup .NET Core v3.1
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 3.1.401

      - name: Restore
        run: dotnet restore

      - name: Build
        run: dotnet build -c Release --no-restore 

      - name: Test
        run: dotnet test -c Release --no-build
      
      - name: Pack
        run: dotnet pack -c Release --no-restore --include-symbols --include-source -p:PackageVersion=$EVENTFLOW_VERSION -p:Version=$EVENTFLOW_VERSION -p:AssemblyVersion=$EVENTFLOW_VERSION

      - name: Upload Artifacts
        uses: actions/upload-artifact@v2
        with:
          name: packages
          path: "./**/EventFlow*${{ env.EVENTFLOW_VERSION}}.*nupkg"

